CREATE DATABASE IF NOT EXISTS MYSQL_DB_NAME;
CREATE USER 'MYSQL_USER_NAME'@'localhost';
SET PASSWORD FOR 'MYSQL_USER_NAME'@'localhost' = PASSWORD('MYSQL_USER_PASSWORD');
GRANT ALL PRIVILEGES ON MYSQL_DB_NAME.* TO 'MYSQL_USER_NAME'@'localhost' IDENTIFIED BY 'MYSQL_USER_PASSWORD';
GRANT ALL ON MYSQL_DB_NAME.* to 'MYSQL_USER_NAME'@'%' IDENTIFIED BY 'MYSQL_USER_PASSWORD';

FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PASS';
flush privileges;
